apiVersion: v1
data:
  "3322": {{.Release.Namespace}}/{{ include "immudb.fullname" . }}-write:3322
  "3323": {{.Release.Namespace}}/{{ include "immudb.fullname" . }}-read:3322
kind: ConfigMap
metadata:
  name: nginx-ingress-tcp-microk8s-conf
  namespace: ingress
