apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immudb-ingress
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
  - host: immudb-write.levy.it
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "immudb.fullname" . }}-write
            port:
              number: 8080
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: {{ include "immudb.fullname" . }}-write
            port:
              number: 9497
  - host: immudb-read.levy.it
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "immudb.fullname" . }}-read
            port:
              number: 8080
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: {{ include "immudb.fullname" . }}-read
            port:
              number: 9497
    {{- $name := include "immudb.fullname" . -}}
    {{- $replicaCount := .Values.replicaCount | int -}}
    {{ range $index0 := until $replicaCount }}
  - host: immudb-read-{{ $index0 }}.levy.it
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}-read-{{ $index0 }}
            port:
              number: 8080
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}-read-{{ $index0 }}
            port:
              number: 9497
    {{ end }}
