apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immudb-ingress
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
  - host: immudb-write.{{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "immudb.fullname" . }}-write
            port:
              number: 8080
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: {{ include "immudb.fullname" . }}-write
            port:
              number: 9497
  - host: immudb-read.{{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "immudb.fullname" . }}-read
            port:
              number: 8080
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: {{ include "immudb.fullname" . }}-read
            port:
              number: 9497
    {{- $hostname := .Values.ingress.hostname -}}
    {{- $name := include "immudb.fullname" . -}}
    {{- $replicaCount := .Values.replicaCount | int -}}
    {{ range $index0 := until $replicaCount }}
  - host: immudb-read-{{ $index0 }}.{{ $hostname }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}-read-{{ $index0 }}
            port:
              number: 8080
      - path: /metrics
        pathType: Prefix
        backend:
          service:
            name: {{ $name }}-read-{{ $index0 }}
            port:
              number: 9497
    {{ end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "public"
spec:
  rules:
  - host: grafana.levy.it
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
