apiVersion: v1
kind: Service
metadata:
  name: {{ include "immudb.fullname" . }}-http
  labels:
    {{- include "immudb.labels" . | nindent 4 }}
    app.kubernetes.io/monitor: immudb-monitor
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "immudb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "immudb.fullname" . }}-grpc
  labels:
    {{- include "immudb.labels" . | nindent 4 }}
  annotations:  
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "immudb.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "immudb.fullname" . }}-read
  labels:
    {{- include "immudb.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
  clusterIP: None
  selector:
    {{- include "immudb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/role: read
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "immudb.fullname" . }}-write
  labels:
    {{- include "immudb.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - name: grpc
      port: {{ .Values.service.ports.grpc }}
  clusterIP: None
  selector:
    {{- include "immudb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/role: write

    {{- $name := include "immudb.fullname" . -}}
    {{- $labels := include "immudb.labels" . | nindent 4 -}}
    {{- $httpPort := .Values.service.ports.http -}}
    {{- $metricsPort := .Values.service.ports.metrics -}}
    {{- $grpcPort := .Values.service.ports.grpc -}}
    {{- $selectorLabels := include "immudb.selectorLabels" . | nindent 4 -}}
    {{- $replicaCount := .Values.replicaCount | int -}}
    {{ range $index0 := until $replicaCount }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}-read-{{ $index0 }}
  labels:    {{ $labels }}
spec:
  ports:
    - port: {{ $httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ $metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    - name: grpc
      port: {{ $grpcPort }}
  clusterIP: None
  selector:    {{ $selectorLabels }}
    app.kubernetes.io/role: read
    statefulset.kubernetes.io/pod-name: {{ $name }}-read-{{ $index0 }}
    {{ end }}
